### ISSUE TITLE
Instrucciones para instalar no funcionan

### ISSUE THREAD

**Issue by Plus17** [resuelve/resuelve-auth-plug#18]
Al intentar instalar la dependencia siguiendo las instrucciones del readme ocurrió el siguiente error:

![image](https://user-images.githubusercontent.com/8551125/84719248-71309b00-af40-11ea-80d3-46113e919313.png)

Es un simple error en el readme, ya que se utilizan tags para el versionamiento.

En el archivo `README.md` cambiar:
```elixir
def deps do
  [{:resuelve_auth, "~> v1.3"}]
end
```
Por:
```elixir
def deps do
  [{:resuelve_auth, github: "resuelve/resuelve-auth-plug", tag: "v1.3"}]
end
```

**Comment by iver** [comment]
Es correcto, las instrucciones están mal. Pero no se usa el tag para obtener las versiones, a partir de la versión 1.2 la notación es:

```elixir
def deps do
  [{:resuelve_auth, "~> 1.3"}]
end
```
