### ISSUE TITLE
Falla al obtener resuelve-auth cuando se usa Poison 4

### ISSUE THREAD

**Issue by Plus17** [resuelve/resuelve-auth-plug#22]
Al intentar obtener `resuelve-auth` y si el `mix.lock` tiene una version mas reciente de poison falla.

### Version de resuelve auth
`{:resuelve_auth, "~> 1.4"}`

![image](https://user-images.githubusercontent.com/8551125/87212459-222e1980-c2e4-11ea-80e9-9a0cfa13f94c.png)

### Posible solución

Podría actualizar la version o sustituir  poison por [Jason](https://github.com/michalmuskala/jason)

**Comment by iver** [comment]
Gracias por el reporte, no me ha sucedido aún pero haré un par de pruebas y empiezo a atenderlo.
